CREATE SEQUENCE hibernate_sequence START 1 INCREMENT 1;

DROP TABLE IF EXISTS LEAVE_OF_ABSENCE;
CREATE TABLE LEAVE_OF_ABSENCE (
    ID 				    BIGINT NOT NULL,
    LEAVE_TYPE		    VARCHAR(255) NOT NULL,
    DESCRIPTION		    VARCHAR(255),
    WORKDAY_ID 		    BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS APP_USER;
CREATE TABLE APP_USER (
    ID 				    BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS WORKTIME;
CREATE TABLE WORKTIME (
    ID 				    BIGINT NOT NULL,
    START_TIME          TIMESTAMP,
    END_TIME            TIMESTAMP,
    WORKDAY_ID 		    VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS OVERTIME;
CREATE TABLE OVERTIME (
    ID 				    BIGINT NOT NULL,
    START_TIME          TIMESTAMP,
    END_TIME            TIMESTAMP,
    WORKDAY_ID 		    VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS WORKDAY;
CREATE TABLE WORKDAY (
    ID 				    VARCHAR(255) NOT NULL,
    VERSION             BIGINT NOT NULL,
    STATUS 			    VARCHAR(255) NOT NULL,
    DAY 			    DATE,
    NOTE 			    VARCHAR(255),
    PRESENCE_TYPE 	    VARCHAR(255),
    BREAK    		    INT8,
    LEAVE_ID 		    BIGINT,
    USER_ID 		    BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

ALTER TABLE WORKDAY ADD CONSTRAINT FK_LEAVE_WORKDAYE FOREIGN KEY (LEAVE_ID) REFERENCES LEAVE_OF_ABSENCE;
ALTER TABLE WORKDAY ADD CONSTRAINT FK_USER_WORKDAY FOREIGN KEY (USER_ID) REFERENCES APP_USER;
ALTER TABLE WORKTIME ADD CONSTRAINT FK_WORKTIME_WORKDAY FOREIGN KEY (WORKDAY_ID) REFERENCES WORKDAY;
ALTER TABLE OVERTIME ADD CONSTRAINT FK_OVERTIME_WORKDAY FOREIGN KEY (WORKDAY_ID) REFERENCES WORKDAY;

INSERT INTO APP_USER VALUES (1);

